;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Event.MeleeSweep",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="AI.StateTree.Events.EnemyChanged",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Elbow.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Elbow.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.High.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.High.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.Low.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.Low.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.Side.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.Side.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.Spinning.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Kick.Spinning.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Knee.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Knee.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Backswing.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Backswing.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Hook.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Hook.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Overhand.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Overhand.Right",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Straight.Cross",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Straight.Jab",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Straight.Jab.Static",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Uppercut.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Attack.Punch.Uppercut.Right",DevComment="")
+GameplayTagList=(Tag="Combat.AttackType.Fast",DevComment="")
+GameplayTagList=(Tag="Combat.AttackType.Heavy",DevComment="")
+GameplayTagList=(Tag="Combat.AttackType.Mid",DevComment="")
+GameplayTagList=(Tag="Combat.Damage.Type.Punch",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Body",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Attribute.Health",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Attribute.Poise",DevComment="")
+GameplayTagList=(Tag="State.InAir",DevComment="")
+GameplayTagList=(Tag="State.Sprinting",DevComment="")
+GameplayTagList=(Tag="State.Staggered",DevComment="")

